version: '3.9'

services:
  tftpserver1:
    container_name: tftpserver1
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    network_mode: "host"
    privileged: true
    ports:
      - "69:69/udp"
    restart: always


  tftpserver2:
    container_name: tftpserver2
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    network_mode: "host"
    privileged: true
    ports:
      - "69:69/udp"
    restart: always

  tftpserver3:
    container_name: tftpserver3
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    network_mode: "host"
    privileged: true
    ports:
      - "69:69/udp"
    restart: always
