version: '3.9'

networks:
  vlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

services:
  tftpserver1:
    container_name: tftpserver1
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      vlan_net:
        ipv4_address: 10.10.10.2
    mac_address: "00:11:22:33:44:10"
    ports:
      - "69:69/udp"
    privileged: true
    restart: always

  tftpserver2:
    container_name: tftpserver2
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      vlan_net:
        ipv4_address: 10.10.10.2
    mac_address: "00:11:22:33:44:20"
    ports:
      - "69:69/udp"
    privileged: true
    restart: always

  tftpserver3:
    container_name: tftpserver3
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      vlan_net:
        ipv4_address: 10.10.10.2
    mac_address: "00:11:22:33:44:30"
    ports:
      - "69:69/udp"
    privileged: true
    restart: always
