version: '3.9'

networks:
  vlan10:
    driver: macvlan
    driver_opts:
      parent: vlan10
  vlan20:
    driver: macvlan
    driver_opts:
      parent: vlan20
  vlan30:
    driver: macvlan
    driver_opts:
      parent: vlan30

services:
  tftpserver1:
    container_name: tftpserver1
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      - vlan10
    ports:
      - "69:69/udp"
    privileged: true
    restart: always


  tftpserver2:
    container_name: tftpserver2
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      - vlan20
    ports:
      - "69:69/udp"
    privileged: true
    restart: always

  tftpserver3:
    container_name: tftpserver3
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - "./data:/tftpshare"
    networks:
      - vlan30
    ports:
      - "69:69/udp"
    privileged: true
    restart: always
